datastore:
  NYC_path: ../data/NYC
  NYC_deltalake_path: ../data/NYC-deltalake
  diabetes_path: ../data/diabetes
  diabetes_deltalake_path: ../data/diabetes-deltalake
datalake:
  endpoint: localhost:9000
  bucket_name_nyc: nyc-dataset
  bucket_name_diabetes: diabetes-dataset
  folder_name_nyc: nyc
  folder_name_diabetes: diabetes
  access_key: minio_access_key
  secret_key: minio_secret_key