apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2023-11-14T09:16:43Z"
  name: tenant1-nodeport-console
  namespace: tenant-ns
  ownerReferences:
  - apiVersion: minio.min.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: tenant1
    uid: e8c3c95c-e3c0-48d1-a08d-2230a12ecfb0
  resourceVersion: "46559"
  uid: 8ad08093-4920-46d4-941c-dc2d8e993cbc
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https-console
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    v1.min.io/tenant: tenant1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
